# docker-compose.yml (fixed) for Food Ordering System (Django)
services:
  web:
    build: .
    container_name: food_ordering_app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
